[MSINTEROP-720] Add functionality to parse services file
RedHatQE/qe-metrics pull request #47
Opened 2024-03-19 19:59 UTC by calebevans

- Adds a class method `from_file` to the `Database.Services` class that is used to parse the "services" file and ensure the services defined in the file are populated in the database.
    - Also adds a `queries` column to the database to hold a JSON blob of queries defined in the file. This is used to match queries to the defined services.
- Adds `verify_queries` to ensure only `blocker` and `critical-blocker` queries will be defined by users. New unit tests for this are added.
- Adds documentation for populating the "services" file.

2024-03-19 19:59 UTC, calebevans commented
/wip

2024-03-19 20:00 UTC, redhat-qe-bot1 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>


</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-03-21 15:21 UTC, calebevans commented
/wip cancel

2024-03-21 15:27 UTC, calebevans commented
/wip cancel

2024-03-22 01:01 UTC, myakove requested changes

2024-03-22 01:01 UTC, myakove commented on qe_metrics/libs/database.py
> +        queries = orm.Required(orm.Json)
`queries`  shouldn't be in the DB, only in the config file.

2024-03-22 13:56 UTC, calebevans commented
/verified

2024-03-22 14:34 UTC, calebevans commented
/verified

2024-03-25 14:04 UTC, calebevans commented
/verified

2024-03-25 14:26 UTC, rnetser approved these changes

2024-03-25 14:26 UTC, merged